# Generated by Django 2.0.4 on 2019-02-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
