# Generated by Django 2.0.4 on 2019-03-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
